### ISSUE TITLE
Feature: Protect handler with GitHub Webhook Secret

### ISSUE THREAD

**Issue by aeshakhzod** [uzinfocom-org/webhook#2]
In the current implementation, any user can send to the open URL hosted on Deno Deploy and spam the Telegram channel/group.

We need the way to handle this scenario @katsuki-yuri

**Comment by orzklv** [comment]
The github secret key has been added whereas service throws error on !config.secret

**Comment by aeshakhzod** [comment]
@katsuki-yuri don't forget to update readme file
